openapi: 3.0.0
info:
  title: Time API
  version: 1.0.0
paths:
  /api/time:
    get:
      summary: Get current time
      operationId: getTime
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
